sudo: false
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y docker-engine
install:
  - echo "Just skip default travis script here :) kthxbye"
before_script:
  - echo "Just skip default travis script here :) kthxbye"
script:
  - ./build-image.sh
